version: '3.3'

networks:
  servicebus:

services:

  tests:
    image: node
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    user: root
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - servicebus
    command: npm run test:staging

  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - servicebus
    ports:
      - 5672:5672
